#!/bin/bash
[[ -d covid-19-data ]] || git clone git@github.com:nytimes/covid-19-data.git

pushd covid-19-data
git pull --rebase
popd

head -1 covid-19-data/us-counties.csv > jefferson.csv
grep "Jefferson,Pen" covid-19-data/us-counties.csv >> jefferson.csv
